import { NewsUnit } from './news-unit';

export const NEWS: NewsUnit[] = [
    { id: 10, title: 'News first Title', date: '15.04.2018', description:'description', img_src: 'img_src', text: 'Ex at co bono gnum nunc ad. Superest is expertus tractant occurrat ut. Multorum deveniri insidias ut at si gurgitem si. Ac gi designabam consuetudo ac patrocinio is spectentur. Rum ego ferri utens vitro prava vulgo eos agi ratio. Nova opus sum cau dat aspi visa vul suae. Rectum ne du ac scient melius. Quaedam figuram dat ita nec nonnisi. Sui volo quam jam vix dum vice vera loco.' },
    { id: 10, title: 'News second Title', date: '17.04.2018', description:'description', img_src: 'img_src', text: 'Id nota ecce illa ut. Creditum meo uti usu vos impressa supponit. Possumus ob loquebar ei pauciora efficiet ineptire alterius ii ab. Conjunctam ope cohibendam perfectior abducendam tum quantumvis. Habendum im suspicio ne perfecta se ac. Hae cui rationum emergere naturali animalia. Progressum mutationum dem distribuam distinctum per eos ego. Sicque mo me doctus eo accepi vultum gi.' },
    { id: 10, title: 'News third Title', date: '22.04.2018', description:'description', img_src: 'img_src', text: 'De meis suum fuse an. Erant vul sua lapis vox sum tanti. Primas ei dicunt et bitavi ea fateri de cogito fueram. Naturalis cunctaque procuravi singulari posterius re ii. Dubitare ut mo lectorem creditum ac judiciis. Finita et factum videor ii ex. Exhibere superest si gi ob ii remanere. ' },
    { id: 10, title: 'News fourth Title', date: '25.04.2018', description:'description', img_src: 'img_src', text: 'Nam est rei prona nobis imo saepe venit autem. Affirmans inspectio subjectum to an ad. Virtutibus falsitatem corporibus quaerendum non est credidisse. Jam ubi iii longo nolle libet lapis illud. Incertas existimo ii ac innotuit mutuatur figmenta de. Pla lectorem vos inquiram eae multarum eos tractare. Ut credere de ea mirabar appello. Nos distinctae imaginandi cohaereant recensenda sap formaliter. Somni atqui visum at eidem ut dicam si et. ' },
    { id: 10, title: 'News fifth Title', date: '27.04.2018', description:'description', img_src: 'img_src', text: 'Supersit de ii rationum du ea momentis cogitari. Seu per qualia humana sumpti una tactum uti. Ne immittit ideamque ac competit ex. Una strepitum imo quibusdam opiniones fas aggrediar. Ex repugnaret aliquoties id in proficisci conjunctam. Age atque vim porro firma negat cupio sequi. Importat seu placidae mei ubi vos quadrati machinae efficere siquidem. Ille hoc ideo amen via fide dum nos. ' },
    { id: 10, title: 'News sixth Title', date: '03.05.2018', description:'description', img_src: 'img_src', text: 'Ab im reducit ac quisnam ut ponamus. Una expectem confusae vigiliam effectus fas. Hac excoluisse dissolvant imo aut communibus. Is quicquid at sufficit tractant excitari et ab. Habeam eamque ima jam juvare seu magnum. Progressum me externarum ne ea immortalem qualitates attingebam quantumvis. Cap corporibus percurrere detorqueat indubitati facultates nam. Sub nec lor debent matura durent itaque. Petitis generis de equidem quandiu ne. Sentiam visione maximam jam tanquam caeteri has dicerem dei. ' }
  ];